### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by volokh0x** [godotengine/godot-git-plugin#128]
I've been trying to compile the plugin as described in `README.md` but ended up with a bunch of errors.

`master`
```
In file included from godot-git-plugin/src/git_callbacks.cpp:7:
godot-git-plugin/src/git_plugin.h:31:35: error: use of undeclared identifier 'ChangeType'
        std::unordered_map<git_status_t, ChangeType> map_changes;
                                         ^
godot-git-plugin/src/git_plugin.h:36:54: error: only virtual member functions can be marked 'override'
        bool _initialize(const godot::String &project_path) override;
                                                            ^~~~~~~~
godot-git-plugin/src/git_plugin.h:37:208: error: only virtual member functions can be marked 'override'
        void _set_credentials(const godot::String &username, const godot::String &password, const godot::String &ssh_public_key_path, const godot::String &ssh_private_key_path, const godot::String &ssh_passphrase) override;
                                                                                                                                                                                                                      ^~~~~~~~
```

`v2.1.0`
```
In file included from godot-git-plugin/src/gdlibrary.cpp:1:
godot-git-plugin/src/git_api.h:7:10: fatal error: 'GodotGlobal.hpp' file not found
#include <GodotGlobal.hpp>
         ^~~~~~~~~~~~~~~~~
```

**Comment by ChronicallySerious** [comment]
Could you show the exact command you are using? Also, have you tried cloning recursively with `git submodule update --init --recursive`?

For the master branch (which is currently only half-working in 4.0b), the process described in the dev section should work - https://github.com/godotengine/godot-git-plugin#dev-builds

You can also just use the extension JSON provided in the root of this repository to build the godot-cpp

**Comment by volokh0x** [comment]
>You can also just use the extension JSON provided in the root of this repository to build the godot-cpp

That's right, I didn't set `custom_api_file` option.

Having two separate json api files in the repository was a bit confusing to me,
and the fact that build process for `godot-git-plugin` requires `custom_api_file` option to be set explicitly unlike in `godot-cpp`

Closing then
