### ISSUE TITLE
[Godot 4 Beta 17] GDExtension plugin crashes editor on startup

### ISSUE THREAD

**Issue by ilovespicynoodles** [godotengine/godot-git-plugin#160]
### Godot version

v4.0.beta17.official.c40020513

### System information

Kernel: x86_64 Linux 6.1.8-zen1-1-zen

### Issue description

Loading my project will instantly crash it with the following error:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta17.official (c40020513ac8201a449b5ae2eeb58fef0ce0a2a4)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x389e0) [0x7fe00f2b49e0] (??:0)
[2] /usr/bin/godot4() [0x45ba731] (??:0)
[3] /usr/bin/godot4() [0x4542e5f] (??:0)
[4] void godot::ClassDB::_register_class<TBLoader, false>(bool) (??:0)
[5] godot::GDExtensionBinding::initialize_level(void*, GDExtensionInitializationLevel) (??:0)
[6] /usr/bin/godot4() [0x45291ab] (??:0)
[7] /usr/bin/godot4() [0xdf32a1] (??:0)
[8] /usr/lib/libc.so.6(+0x23290) [0x7fe00f29f290] (??:0)
[9] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fe00f29f34a] (??:0)
[10] /usr/bin/godot4() [0xe0908e] (??:0)
-- END OF BACKTRACE --
================================================================
```
Removing the plugins in the `extension_list.cfg` in my project folder let me load the project, but after enabling for example only the git plugin extension, it crashes again with:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta17.official (c40020513ac8201a449b5ae2eeb58fef0ce0a2a4)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x389e0) [0x7f2f746a79e0] (??:0)
[2] [0xb737000] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Having any plugins/extensions in my project crashes it immediately on load.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I transferred the issue to the git plugin repo. CC @twaritwaikar

**Comment by kuxv** [comment]
it is the same on RC1

**Comment by RobertoMaurizzi** [comment]
> You can also update the `godot-cpp` submodule and try to compile it, which might solve the issue, if it compiles.

I just tried compiling it: cloned the repo with --recursive, updated godot_cpp to `master` then ran `scons target=editor generate_bindings=yes dev_build=yes gdextension_dir="/c/Users/myuser/whereIputthe2files/" -j 6` and after quite a bit of compiling I got the following (repeated a couple of times):

```
C:\Users\...\Documents\Devel\Godot_dev\godot-git-plugin\godot-git-plugin\src\git_plugin.h(43): error C3668: 'GitPlugin::_get_diff': method with override specifier 'override' did not override any base class methods
C:\Users\...\Documents\Devel\Godot_dev\godot-git-plugin\godot-git-plugin\src\git_plugin.h(46): error C3668: 'GitPlugin::_get_previous_commits': method with override specifier 'override' did not override any base class methods
```

**Comment by RobertoMaurizzi** [comment]
Update: `godot-cpp` released a commit described as "compatible with RC3"...

I tried to compile the plugin using that and it's the same (errors in git_plugin.h). By actually removing the `override` keyword the code compiles, but then the plugin interface doesn't show up 😅 (the two classes don't sound related to integration with the editor, so it might be due to some other mistake I'm making in building the plugin).

I removed the dev_build=yes because it turned out that default scons for the editor isn't building a dev version so the editor is searching for `libgit_plugin.windows.editor.x86_64.dll` instead of `libgit_plugin.windows.editor.dev.x86_64.dll`

**Comment by akien-mga** [comment]
For those of you who can compile from source, please test #161. I didn't get to test it myself but it compiles and should work with Godot 4.0 RC 4.

**Comment by akien-mga** [comment]
I tagged a new v3.0.0-beta2 release with this fix: https://github.com/godotengine/godot-git-plugin/releases/tag/v3.0.0-beta2

And it's updated on the Asset Library too: https://godotengine.org/asset-library/asset/1581

It's compatible with 4.0 RC 4, possibly with some of the older RCs, and should work fine with 4.0-stable too (but we'll make a new release by then to be fully in sync with the latest godot-cpp).

**Comment by RobertoMaurizzi** [comment]
I tried the new version and it compiles clean plus it doesn't crash the editor anymore.
However, I can't get it to work even with the official RC-5 + the plugin downloaded from assets.
I opened a new issue #163 for that.

**Comment by ilovespicynoodles** [comment]
After installing Godot 4 stable 1, it stopped being an issue :)
