### ISSUE TITLE
Not able to compile it for windows 32bit

### ISSUE THREAD

**Issue by GumaD3v** [godotengine/godot-git-plugin#110]
I tryed to compile it adding the 32 bit options to the SConstruct file. but it failed for missing files, is this a problem only for me

**Comment by Calinou** [comment]
Can you paste the full console log here? Without this information, it's impossible for us to do anything.

**Comment by ChronicallySerious** [comment]
I recall there being some patch notes from one of our dependency libraries about removing 32 bit support. This would be something to investigate in depth before making any conclusions

**Comment by GumaD3v** [comment]
I'm using win7 32bit, i've ran this command: scons platform=windows target=release bits=32-j 6
To get this log:
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fogodot-git-plugin\src\gdlibrary.obj /c godot-git-plugin\src\gdlibrary.cpp /
TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:c+
+17 -O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-cpp
\godot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\
gen /Ithirdparty\git2\libgit2\include
cl /Fogodot-git-plugin\src\git_api.obj /c godot-git-plugin\src\git_api.cpp /TP /
nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:c++17
-O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-cpp\god
ot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen
/Ithirdparty\git2\libgit2\include
gdlibrary.cpp
cl /Fogodot-git-plugin\src\git_common.obj /c godot-git-plugin\src\git_common.cpp
 /TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:
c++17 -O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-c
pp\godot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\includ
e\gen /Ithirdparty\git2\libgit2\include
git_api.cpp
git_common.cpp
cl /Fothirdparty\git2\libgit2\src\cherrypick.obj /c thirdparty\git2\libgit2\src\
cherrypick.c /nologo /DGIT_WINHTTP /DHAVE_SYS_STAT_H /DHAVE_SYS_TYPES_H /DHAVE_W
INDOWS_H /DHAVE_STDINT_H /DHAVE_INTTYPES_H /DHAVE_MEMMOVE /DHAVE_STRERROR /DHAVE
_STRTOLL /DHAVE__STRTOI64 /DSUPPORT_PCRE8 /DNO_RECURSE /DHAVE_LONG_LONG /DHAVE_U
NSIGNED_LONG_LONG /DNEWLINE=10 /DPOSIX_MALLOC_THRESHOLD=10 /DLINK_SIZE=2 /DPAREN
S_NEST_LIMIT=250 /DMATCH_LIMIT=10000000 /DMATCH_LIMIT_RECURSION=10000000 /DPCREG
REP_BUFSIZE /DMAX_NAME_SIZE=32 /DMAX_NAME_COUNT=10000 /DHAVE_WINCNG /DLIBSSH2_WI
NCNG /DGIT_THREADS /DGIT_SSH /DGIT_SSH_MEMORY_CREDENTIALS /DLIBGIT2_NO_FEATURES_
H /DGIT_SHA1_COLLISIONDETECT /DGIT_HTTPS /DSRC_UTIL_H_ /DGIT_REGEX_BUILTIN /Ithi
rdparty\git2\libgit2\include /Ithirdparty\git2\libgit2\src /Ithirdparty\git2\lib
git2\deps\http-parser /Ithirdparty\git2\libgit2\deps\pcre /Ithirdparty\git2\libg
it2\deps\zlib /Ithirdparty\git2\libgit2\deps\ntlmclient /Ithirdparty\ssh2\libssh
2\include
cl /Fothirdparty\git2\libgit2\src\clone.obj /c thirdparty\git2\libgit2\src\clone
.c /nologo /DGIT_WINHTTP /DHAVE_SYS_STAT_H /DHAVE_SYS_TYPES_H /DHAVE_WINDOWS_H /
DHAVE_STDINT_H /DHAVE_INTTYPES_H /DHAVE_MEMMOVE /DHAVE_STRERROR /DHAVE_STRTOLL /
DHAVE__STRTOI64 /DSUPPORT_PCRE8 /DNO_RECURSE /DHAVE_LONG_LONG /DHAVE_UNSIGNED_LO
NG_LONG /DNEWLINE=10 /DPOSIX_MALLOC_THRESHOLD=10 /DLINK_SIZE=2 /DPARENS_NEST_LIM
IT=250 /DMATCH_LIMIT=10000000 /DMATCH_LIMIT_RECURSION=10000000 /DPCREGREP_BUFSIZ
E /DMAX_NAME_SIZE=32 /DMAX_NAME_COUNT=10000 /DHAVE_WINCNG /DLIBSSH2_WINCNG /DGIT
_THREADS /DGIT_SSH /DGIT_SSH_MEMORY_CREDENTIALS /DLIBGIT2_NO_FEATURES_H /DGIT_SH
A1_COLLISIONDETECT /DGIT_HTTPS /DSRC_UTIL_H_ /DGIT_REGEX_BUILTIN /Ithirdparty\gi
t2\libgit2\include /Ithirdparty\git2\libgit2\src /Ithirdparty\git2\libgit2\deps\
http-parser /Ithirdparty\git2\libgit2\deps\pcre /Ithirdparty\git2\libgit2\deps\z
lib /Ithirdparty\git2\libgit2\deps\ntlmclient /Ithirdparty\ssh2\libssh2\include
cl /Fothirdparty\git2\libgit2\src\commit.obj /c thirdparty\git2\libgit2\src\comm
it.c /nologo /DGIT_WINHTTP /DHAVE_SYS_STAT_H /DHAVE_SYS_TYPES_H /DHAVE_WINDOWS_H
 /DHAVE_STDINT_H /DHAVE_INTTYPES_H /DHAVE_MEMMOVE /DHAVE_STRERROR /DHAVE_STRTOLL
 /DHAVE__STRTOI64 /DSUPPORT_PCRE8 /DNO_RECURSE /DHAVE_LONG_LONG /DHAVE_UNSIGNED_
LONG_LONG /DNEWLINE=10 /DPOSIX_MALLOC_THRESHOLD=10 /DLINK_SIZE=2 /DPARENS_NEST_L
IMIT=250 /DMATCH_LIMIT=10000000 /DMATCH_LIMIT_RECURSION=10000000 /DPCREGREP_BUFS
IZE /DMAX_NAME_SIZE=32 /DMAX_NAME_COUNT=10000 /DHAVE_WINCNG /DLIBSSH2_WINCNG /DG
IT_THREADS /DGIT_SSH /DGIT_SSH_MEMORY_CREDENTIALS /DLIBGIT2_NO_FEATURES_H /DGIT_
SHA1_COLLISIONDETECT /DGIT_HTTPS /DSRC_UTIL_H_ /DGIT_REGEX_BUILTIN /Ithirdparty\
git2\libgit2\include /Ithirdparty\git2\libgit2\src /Ithirdparty\git2\libgit2\dep
s\http-parser /Ithirdparty\git2\libgit2\deps\pcre /Ithirdparty\git2\libgit2\deps
\zlib /Ithirdparty\git2\libgit2\deps\ntlmclient /Ithirdparty\ssh2\libssh2\includ
e
clone.c
commit.c
cherrypick.c
C:\Users\Gumagu\Documents\Godot\godot-git-plugin\godot-git-plugin\src\git_api
.h(8): fatal error C1083: Non è possibile aprire il file inclusione: 'AcceptDial
og.hpp': No such file or directory
scons: *** [godot-git-plugin\src\git_api.obj] Error 2
C:\Users\Gumagu\Documents\Godot\godot-git-plugin\godot-git-plugin\src\git_api
.h(8): fatal error C1083: Non è possibile aprire il file inclusione: 'AcceptDial
og.hpp': No such file or directory
scons: *** [godot-git-plugin\src\gdlibrary.obj] Error 2
C:\Users\Gumagu\Documents\Godot\godot-git-plugin\godot-cpp\include\core\Ref.h
pp(35): fatal error C1083: Non è possibile aprire il file inclusione: 'Reference
.hpp': No such file or directory
scons: *** [godot-git-plugin\src\git_common.obj] Error 2
scons: building terminated because of errors.

**Comment by ChronicallySerious** [comment]
@GumaD3v Can you confirm if you have recursively cloned this repository? godot-cpp uses godot-headers as a submodule, so you might have to run `git submodule update --init` to get those sources. 

Also, once you do that, you will have to use the 'godot_cpp=yes` argument when you run SCons for the reason mentioned in the README under 'Bleeding Edge'.

**Comment by GumaD3v** [comment]
Tryed: i got this error
cl /Fogodot-cpp\src\gen\__register_types.obj /c godot-cpp\src\gen\__register_typ
es.cpp /TP /nologo /O2 /EHsc /DNDEBUG /MD /Igodot-cpp /Igodot-cpp\godot-headers
/Igodot-cpp\include /Igodot-cpp\include\gen /Igodot-cpp\include\core
__init_method_bindings.cpp
__register_types.cpp
cl /Fogodot-git-plugin\src\gdlibrary.obj /c godot-git-plugin\src\gdlibrary.cpp /
TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:c+
+17 -O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-cpp
\godot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\
gen /Ithirdparty\git2\libgit2\include
gdlibrary.cpp
cl /Fogodot-git-plugin\src\git_api.obj /c godot-git-plugin\src\git_api.cpp /TP /
nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:c++17
-O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-cpp\god
ot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen
/Ithirdparty\git2\libgit2\include
git_api.cpp
cl /Fogodot-git-plugin\src\git_common.obj /c godot-git-plugin\src\git_common.cpp
 /TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS /std:
c++17 -O2 -EHsc -DNDEBUG -MD /Igodot-git-plugin /Igodot-git-plugin\src /Igodot-c
pp\godot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\includ
e\gen /Ithirdparty\git2\libgit2\include
git_common.cpp
godot-git-plugin\src\git_api.cpp(73): error C3861: 'popup_error': identificatore
 non trovato
cl /Fothirdparty\git2\libgit2\src\commit_graph.obj /c thirdparty\git2\libgit2\sr
c\commit_graph.c /nologo /DGIT_WINHTTP /DHAVE_SYS_STAT_H /DHAVE_SYS_TYPES_H /DHA
VE_WINDOWS_H /DHAVE_STDINT_H /DHAVE_INTTYPES_H /DHAVE_MEMMOVE /DHAVE_STRERROR /D
HAVE_STRTOLL /DHAVE__STRTOI64 /DSUPPORT_PCRE8 /DNO_RECURSE /DHAVE_LONG_LONG /DHA
VE_UNSIGNED_LONG_LONG /DNEWLINE=10 /DPOSIX_MALLOC_THRESHOLD=10 /DLINK_SIZE=2 /DP
ARENS_NEST_LIMIT=250 /DMATCH_LIMIT=10000000 /DMATCH_LIMIT_RECURSION=10000000 /DP
CREGREP_BUFSIZE /DMAX_NAME_SIZE=32 /DMAX_NAME_COUNT=10000 /DHAVE_WINCNG /DLIBSSH
2_WINCNG /DGIT_THREADS /DGIT_SSH /DGIT_SSH_MEMORY_CREDENTIALS /DLIBGIT2_NO_FEATU
RES_H /DGIT_SHA1_COLLISIONDETECT /DGIT_HTTPS /DSRC_UTIL_H_ /DGIT_REGEX_BUILTIN /
Ithirdparty\git2\libgit2\include /Ithirdparty\git2\libgit2\src /Ithirdparty\git2
\libgit2\deps\http-parser /Ithirdparty\git2\libgit2\deps\pcre /Ithirdparty\git2\
libgit2\deps\zlib /Ithirdparty\git2\libgit2\deps\ntlmclient /Ithirdparty\ssh2\li
bssh2\include
godot-git-plugin\src\git_api.cpp(258): error C2065: 'CHANGE_TYPE_NEW': identific
atore non dichiarato
godot-git-plugin\src\git_api.cpp(259): error C2065: 'CHANGE_TYPE_NEW': identific
atore non dichiarato
godot-git-plugin\src\git_api.cpp(260): error C2065: 'CHANGE_TYPE_MODIFIED': iden
tificatore non dichiarato
godot-git-plugin\src\git_api.cpp(261): error C2065: 'CHANGE_TYPE_MODIFIED': iden
tificatore non dichiarato
godot-git-plugin\src\git_api.cpp(262): error C2065: 'CHANGE_TYPE_RENAMED': ident
ificatore non dichiarato
godot-git-plugin\src\git_api.cpp(263): error C2065: 'CHANGE_TYPE_RENAMED': ident
ificatore non dichiarato
godot-git-plugin\src\git_api.cpp(264): error C2065: 'CHANGE_TYPE_DELETED': ident
ificatore non dichiarato
godot-git-plugin\src\git_api.cpp(265): error C2065: 'CHANGE_TYPE_DELETED': ident
ificatore non dichiarato
godot-git-plugin\src\git_api.cpp(266): error C2065: 'CHANGE_TYPE_TYPECHANGE': id
entificatore non dichiarato
godot-git-plugin\src\git_api.cpp(267): error C2065: 'CHANGE_TYPE_TYPECHANGE': id
entificatore non dichiarato
godot-git-plugin\src\git_api.cpp(268): error C2065: 'CHANGE_TYPE_UNMERGED': iden
tificatore non dichiarato
godot-git-plugin\src\git_api.cpp(274): error C2065: 'TREE_AREA_UNSTAGED': identi
ficatore non dichiarato
godot-git-plugin\src\git_api.cpp(274): error C3861: 'create_status_file': identi
ficatore non trovato
godot-git-plugin\src\git_api.cpp(280): error C2065: 'TREE_AREA_STAGED': identifi
catore non dichiarato
godot-git-plugin\src\git_api.cpp(280): error C3861: 'create_status_file': identi
ficatore non trovato
godot-git-plugin\src\git_api.cpp(281): error C2065: 'TREE_AREA_STAGED': identifi
catore non dichiarato
godot-git-plugin\src\git_api.cpp(281): error C3861: 'create_status_file': identi
ficatore non trovato
godot-git-plugin\src\git_api.cpp(283): error C2065: 'TREE_AREA_STAGED': identifi
catore non dichiarato
godot-git-plugin\src\git_api.cpp(283): error C3861: 'create_status_file': identi
ficatore non trovato
godot-git-plugin\src\git_common.cpp(102): error C2039: 'create_diff_hunk': non è
 un membro di 'godot::GitAPI'godot-git-plugin\src\git_api.cpp(393): warning C401
8: '<': errata corrispondenza tra signed e unsigned

godot-git-plugin\src\git_api.h(104): note: vedere la dichiarazione di 'godot::Gi
tAPI'
scons: *** [godot-git-plugin\src\git_common.obj] Error 2
cl /Fothirdparty\git2\libgit2\src\commit_list.obj /c thirdparty\git2\libgit2\src
\commit_list.c /nologo /DGIT_WINHTTP /DHAVE_SYS_STAT_H /DHAVE_SYS_TYPES_H /DHAVE
_WINDOWS_H /DHAVE_STDINT_H /DHAVE_INTTYPES_H /DHAVE_MEMMOVE /DHAVE_STRERROR /DHA
VE_STRTOLL /DHAVE__STRTOI64 /DSUPPORT_PCRE8 /DNO_RECURSE /DHAVE_LONG_LONG /DHAVE
_UNSIGNED_LONG_LONG /DNEWLINE=10 /DPOSIX_MALLOC_THRESHOLD=10 /DLINK_SIZE=2 /DPAR
ENS_NEST_LIMIT=250 /DMATCH_LIMIT=10000000 /DMATCH_LIMIT_RECURSION=10000000 /DPCR
EGREP_BUFSIZE /DMAX_NAME_SIZE=32 /DMAX_NAME_COUNT=10000 /DHAVE_WINCNG /DLIBSSH2_
WINCNG /DGIT_THREADS /DGIT_SSH /DGIT_SSH_MEMORY_CREDENTIALS /DLIBGIT2_NO_FEATURE
S_H /DGIT_SHA1_COLLISIONDETECT /DGIT_HTTPS /DSRC_UTIL_H_ /DGIT_REGEX_BUILTIN /It
hirdparty\git2\libgit2\include /Ithirdparty\git2\libgit2\src /Ithirdparty\git2\l
ibgit2\deps\http-parser /Ithirdparty\git2\libgit2\deps\pcre /Ithirdparty\git2\li
bgit2\deps\zlib /Ithirdparty\git2\libgit2\deps\ntlmclient /Ithirdparty\ssh2\libs
sh2\include
godot-git-plugin\src\git_api.cpp(420): error C3861: 'create_commit': identificat
ore non trovato
godot-git-plugin\src\git_api.cpp(483): error C3861: 'popup_error': identificator
e non trovato
commit_graph.c
godot-git-plugin\src\git_api.cpp(528): error C3861: 'popup_error': identificator
e non trovato
godot-git-plugin\src\git_api.cpp(530): error C3861: 'popup_error': identificator
e non trovato
godot-git-plugin\src\git_api.cpp(606): error C2065: 'TreeArea': identificatore n
on dichiarato
godot-git-plugin\src\git_api.cpp(606): error C2146: errore di sintassi: ')' manc
ante prima dell'identificatore 'area'
godot-git-plugin\src\git_api.cpp(606): error C2050: espressione switch non integ
rale
godot-git-plugin\src\git_api.cpp(606): error C2059: errore di sintassi: ')'
godot-git-plugin\src\git_api.cpp(607): error C2059: errore di sintassi: 'case'
godot-git-plugin\src\git_api.cpp(607): error C2143: errore di sintassi: ';' manc
ante prima di '{'
commit_list.c
godot-git-plugin\src\git_api.cpp(610): error C2065: 'TREE_AREA_STAGED': identifi
catore non dichiarato
godot-git-plugin\src\git_api.cpp(610): error C2046: case non valido
godot-git-plugin\src\git_api.cpp(623): error C2065: 'TREE_AREA_COMMIT': identifi
catore non dichiarato
godot-git-plugin\src\git_api.cpp(623): error C2046: case non valido
godot-git-plugin\src\git_api.cpp(607): warning C4060: istruzione switch senza et
ichette 'case' o 'default'
godot-git-plugin\src\git_api.cpp(609): error C2043: break non valido
godot-git-plugin\src\git_api.cpp(622): error C2043: break non valido
godot-git-plugin\src\git_api.cpp(646): error C2043: break non valido
godot-git-plugin\src\git_api.cpp(649): error C4430: identificatore di tipo manca
nte, verrà utilizzato int. Nota: default-int non è più supportato in C++
godot-git-plugin\src\git_api.cpp(649): error C2065: 'diff': identificatore non d
ichiarato
godot-git-plugin\src\git_api.cpp(649): error C3861: '_parse_diff': identificator
e non trovato
godot-git-plugin\src\git_api.cpp(651): error C2059: errore di sintassi: 'return'

godot-git-plugin\src\git_api.cpp(654): error C2653: 'GitAPI' non è il nome di un
a classe o di uno spazio dei nomi
godot-git-plugin\src\git_api.cpp(654): error C4430: identificatore di tipo manca
nte, verrà utilizzato int. Nota: default-int non è più supportato in C++
godot-git-plugin\src\git_api.cpp(654): error C2146: errore di sintassi: ';' manc
ante prima dell'identificatore '_parse_diff'
godot-git-plugin\src\git_api.cpp(654): error C2143: errore di sintassi: ';' manc
ante prima di '{'
godot-git-plugin\src\git_api.cpp(654): error C2447: '{': intestazione di funzion
e mancante. Elenco formale di tipo obsoleto?
godot-git-plugin\src\git_api.cpp(695): error C2653: 'GitAPI' non è il nome di un
a classe o di uno spazio dei nomi
godot-git-plugin\src\git_api.cpp(695): error C4430: identificatore di tipo manca
nte, verrà utilizzato int. Nota: default-int non è più supportato in C++
godot-git-plugin\src\git_api.cpp(695): error C2146: errore di sintassi: ';' manc
ante prima dell'identificatore '_get_vcs_name'
godot-git-plugin\src\git_api.cpp(695): error C2143: errore di sintassi: ';' manc
ante prima di '{'
godot-git-plugin\src\git_api.cpp(695): error C2447: '{': intestazione di funzion
e mancante. Elenco formale di tipo obsoleto?
godot-git-plugin\src\git_api.cpp(699): error C2653: 'GitAPI' non è il nome di un
a classe o di uno spazio dei nomi
godot-git-plugin\src\git_api.cpp(699): error C2146: errore di sintassi: ')' manc
ante prima dell'identificatore 'project_path'
godot-git-plugin\src\git_api.cpp(699): error C2143: errore di sintassi: ';' manc
ante prima di '{'
godot-git-plugin\src\git_api.cpp(699): error C2447: '{': intestazione di funzion
e mancante. Elenco formale di tipo obsoleto?
godot-git-plugin\src\git_api.cpp(719): error C2653: 'GitAPI' non è il nome di un
a classe o di uno spazio dei nomi
godot-git-plugin\src\git_api.cpp(720): error C2065: 'repo': identificatore non d
ichiarato
godot-git-plugin\src\git_api.cpp(721): error C3861: 'check_errors': identificato
re non trovato
godot-git-plugin\src\git_api.cpp(725): error C2653: 'GitAPI' non è il nome di un
a classe o di uno spazio dei nomi
godot-git-plugin\src\git_api.cpp(728): error C2059: errore di sintassi: '}'
godot-git-plugin\src\git_api.cpp(728): error C2143: errore di sintassi: ';' manc
ante prima di '}'
scons: *** [godot-git-plugin\src\git_api.obj] Error 2
scons: building terminated because of errors.

**Comment by ChronicallySerious** [comment]
@GumaD3v This might be because you are using the standard godot-cpp version that is checked into this repository. Since Godot 3.5 is currently in beta, you will have to use a "simple" workaround to compile the master branch of this plugin, by running:

```shell
scons platform=windows target=debug godot_cpp=yes generate_bindings=yes bits=32 use_custom_api_file=yes custom_api_file=api.ci.json -j 6
```

Please note that the master branch of this plugin only works in Godot 3.5 builds currently.
